name: Publish packages to npmjs

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          scope: "@nimblehq"

      - name: Install dependencies
        run: npm ci && lerna bootstrap --ci

      - name: Publish packages to npmjs
        run: npx lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
