name: Publish packages to npmjs

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "18"

jobs:
  publish:
    name: Publish packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          scope: "@nimblehq"

      - name: Install dependencies
        run: npm ci

      - name: Publish packages to npmjs
        run: npx lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
